### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by ethanclevenger91** [nymo/gulp-tinypng-extended#16]
```warning elixir-tinypng > gulp-tinypng-extended > request > node-uuid@1.4.8: Use uuid module instead```

Thoughts?

**Comment by nymo** [comment]
We should update the request package. They moved already to the new uuid module.

**Comment by nymo** [comment]
@ethanclevenger91 please use latest Version 2.0.0. There should be no deprecation messages anymore.
