### ISSUE TITLE
502 gateway timeout should not stop plugin

### ISSUE THREAD

**Issue by nymo** [nymo/gulp-tinypng-extended#7]
If the API returns an 502 gateway timeout the plugin should not stop the process of the img generation and continue with a timeout of some seconds or just contiune and ignore the gateway timeout. Because on a break the signature files are not being written and you start again with the first file which is bad because your api counts are used twice for the same files.

Another solution could be to write the signature file on a break to keep the information about the already compressed images.

**Comment by cspicuzza** [comment]
I back this!

**Comment by nymo** [comment]
@cspicuzza should work now.
